// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7HLEI_kiTYsowrcAt66xXOkUpgVE7Oqw',
    appId: '1:688667436303:web:aabefd40a908e291b50a7a',
    messagingSenderId: '688667436303',
    projectId: 'calories-tracking-fb637',
    authDomain: 'calories-tracking-fb637.firebaseapp.com',
    storageBucket: 'calories-tracking-fb637.firebasestorage.app',
    measurementId: 'G-EJKB31D103',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbAbsxDXRfAoDS8NlV5xIsLMA2XemJOL0',
    appId: '1:688667436303:android:f07ca8cd16d96dbeb50a7a',
    messagingSenderId: '688667436303',
    projectId: 'calories-tracking-fb637',
    storageBucket: 'calories-tracking-fb637.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeSWUDloHcfBlmaZRaDRIC_NKrQHI8Orc',
    appId: '1:688667436303:ios:975ebecfbab5eba2b50a7a',
    messagingSenderId: '688667436303',
    projectId: 'calories-tracking-fb637',
    storageBucket: 'calories-tracking-fb637.firebasestorage.app',
    iosBundleId: 'com.example.caloriesTracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeSWUDloHcfBlmaZRaDRIC_NKrQHI8Orc',
    appId: '1:688667436303:ios:975ebecfbab5eba2b50a7a',
    messagingSenderId: '688667436303',
    projectId: 'calories-tracking-fb637',
    storageBucket: 'calories-tracking-fb637.firebasestorage.app',
    iosBundleId: 'com.example.caloriesTracking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7HLEI_kiTYsowrcAt66xXOkUpgVE7Oqw',
    appId: '1:688667436303:web:211fe13bb322bfd9b50a7a',
    messagingSenderId: '688667436303',
    projectId: 'calories-tracking-fb637',
    authDomain: 'calories-tracking-fb637.firebaseapp.com',
    storageBucket: 'calories-tracking-fb637.firebasestorage.app',
    measurementId: 'G-8QVCK251W9',
  );
}
